MotorsportsEncyclopedia/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MotorsportsEncyclopedia.Models
{
	public class Car
	{
		public int? CarID { get; set; }
		public int CarYear { get; set; }
		[Required]
		[StringLength(100, ErrorMessage = "Car make cannot be longer than 100 characters.")]
		public string CarMake { get; set; }
		[Required]
		[StringLength(100, ErrorMessage = "Car name cannot be longer than 100 characters.")]
		public string CarName { get; set; }
		public string CarDescription { get; set; }

		public virtual ICollection<Enrollment> Enrollments { get; set; }
	}
}

MotorsportsEncyclopedia/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MotorsportsEncyclopedia.DAL;
using MotorsportsEncyclopedia.Models;
using PagedList;

namespace MotorsportsEncyclopedia.Controllers
{
    public class CarController : Controller
    {
        private EncyclopediaContext db = new EncyclopediaContext();

		// GET: Car
		public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
		{
			ViewBag.CurrentSort = sortOrder;
			ViewBag.intSortParm = sortOrder == "Year" ? "year_desc" : "Year";
			ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "make_desc" : "";
			ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

			if (searchString != null)
			{
				page = 1;
			}
			else
			{
				searchString = currentFilter;
			}

			ViewBag.CurrentFilter = searchString;

			var cars = from c in db.Cars
						   select c;
			if (!String.IsNullOrEmpty(searchString))
			{
				cars = cars.Where(c => c.CarName.Contains(searchString)
									   || c.CarMake.Contains(searchString));
			}
			switch (sortOrder)
			{
				case "Year":
					cars = cars.OrderBy(c => c.CarYear);
					break;
				case "year_desc":
					cars = cars.OrderByDescending(c => c.CarYear);
					break;
				case "make_desc":
					cars = cars.OrderByDescending(c => c.CarMake);
					break;
				case "name_desc":
					cars = cars.OrderByDescending(c => c.CarName);
					break;
				default:
					cars = cars.OrderBy(c => c.CarYear);
					break;
			}
			int pageSize = 10;
			int pageNumber = (page ?? 1);
			return View(cars.ToPagedList(pageNumber, pageSize));
		}

		public void Create(int v1, string v2, string v3, string v4)
		{
			throw new NotImplementedException();
		}

		// GET: Car/Details/5
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Car/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Car/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "CarYear, CarMake, CarName, CarDescription")]Car car)
		{
			try
			{
				if (ModelState.IsValid)
				{
					db.Cars.Add(car);
					db.SaveChanges();
					return RedirectToAction("Index");
				}
			}
			catch (DataException /* dex */)
			{
				//Log the error (uncomment dex variable name and add a line here to write a log.
				ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
			}
			return View(car);
        }

        // GET: Car/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

		// POST: Car/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost, ActionName("Edit")]
		[ValidateAntiForgeryToken]
		public ActionResult EditPost(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var carToUpdate = db.Cars.Find(id);
			if (TryUpdateModel(carToUpdate, "",
			   new string[] { "CarYear", "CarMake", "CarName", "CarDescription" }))
			{
				try
				{
					db.SaveChanges();

					return RedirectToAction("Index");
				}
				catch (DataException /* dex */)
				{
					//Log the error (uncomment dex variable name and add a line here to write a log.
					ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
				}
			}
			return View(carToUpdate);
		}

		// GET: Car/Delete/5
		public ActionResult Delete(int? id, bool? saveChangesError = false)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			if (saveChangesError.GetValueOrDefault())
			{
				ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";
			}
			Car car = db.Cars.Find(id);
			if (car == null)
			{
				return HttpNotFound();
			}
			return View(car);
		}

		// POST: Car/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id)
		{
			try
			{
				Car car = db.Cars.Find(id);
				db.Cars.Remove(car);
				db.SaveChanges();
			}
			catch (DataException/* dex */)
			{
				//Log the error (uncomment dex variable name and add a line here to write a log.
				return RedirectToAction("Delete", new { id = id, saveChangesError = true });
			}
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MotorsportsEncyclopedia/Views/Car/Create.cshtml
@model MotorsportsEncyclopedia.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CarYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarMake, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarMake, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarMake, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MotorsportsEncyclopedia/Views/Car/Delete.cshtml
@model MotorsportsEncyclopedia.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<p class="error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarMake)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarMake)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MotorsportsEncyclopedia/Views/Car/Details.cshtml
@model MotorsportsEncyclopedia.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CarYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarMake)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarMake)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Enrollments)
        </dt>

        <dd>
            <table class="table">
                <tr>
                    <th>Track Title</th>
                    <th>Lap Time</th>
                </tr>
                @foreach (var item in Model.Enrollments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Track.TrackName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LapTime)
                        </td>
                    </tr>}
            </table>
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CarID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MotorsportsEncyclopedia/Views/Car/Edit.cshtml
@model MotorsportsEncyclopedia.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CarID)

        <div class="form-group">
            @Html.LabelFor(model => model.CarYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarMake, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarMake, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarMake, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MotorsportsEncyclopedia/Views/Car/Index.cshtml
@model PagedList.IPagedList<MotorsportsEncyclopedia.Models.Car>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Cars";
}

<h2>Cars</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Car", FormMethod.Get))
{
    <p>
        Find by name and and make: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Car Year", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Car Make", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Car Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Car Description
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CarYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarMake)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CarID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CarID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CarID })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))